from microbit import *

MOTOR_LEFT_FORWARD_PIN = pin0
MOTOR_LEFT_BACKWARD_PIN = pin1
MOTOR_RIGHT_FORWARD_PIN = pin2
MOTOR_RIGHT_BACKWARD_PIN = pin8

MIN_MOTOR_SPEED = 200
MAX_MOTOR_SPEED = 1023
DEFAULT_MOTOR_SPEED = 600

stored_encrypted_face_data = None